# Test Case: API Endpoints
name = "API Endpoints Implementation"
description = "Query about REST API endpoints and routing"
query = "how are API endpoints defined and routed"
project_root = "benchmarks/test_repositories/valor"

# Expected relevant files
[[expected]]
path = "crates/api/src/lib.rs"
priority = "critical"
reason = "API module entry point"

[[expected]]
path = "crates/api/src/routes.rs"
priority = "critical"
reason = "Route definitions"

[[expected]]
path = "crates/api/src/handlers.rs"
priority = "high"
reason = "Request handlers"

[[expected]]
path = "crates/api/src/middleware.rs"
priority = "medium"
reason = "API middleware"

[[expected]]
path = "crates/server/src/lib.rs"
priority = "medium"
reason = "Server implementation"

# Files that should NOT appear
[[excluded]]
path = "crates/css"
reason = "CSS parsing, not API"

[[excluded]]
path = "crates/dom"
reason = "DOM tree, not API"
