[package]
name = "agentic-providers"
version.workspace = true
edition.workspace = true

[dependencies]
agentic-core.workspace = true
async-trait = "0.1"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
