name: "Setup Rust"
description: "Installs Rust toolchain, components, tools, and caching"
inputs:
  components:
    description: "Additional Rust components to install (comma-separated)"
    required: false
    default: ""
  tools:
    description: "Cargo tools to install via taiki-e/install-action (comma-separated)"
    required: false
    default: ""
  cache-key:
    description: "Additional cache key suffix"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout test repository
      uses: actions/checkout@v4
      with:
        repository: 'BigBadE/valor'
        path: benchmarks/crates/quality/test_repositories/valor

    - name: Setup fast cargo config
      shell: bash
      run: |
        if [ -f .cargo/fast_config.toml ]; then
          cp .cargo/fast_config.toml .cargo/config.toml
        fi

    - name: Install Rust toolchain
      shell: bash
      run: rustup show

    - name: Install additional components
      if: inputs.components != ''
      shell: bash
      run: |
        IFS=',' read -ra COMPONENTS <<< "${{ inputs.components }}"
        for component in "${COMPONENTS[@]}"; do
          component=$(echo "$component" | xargs)  # trim whitespace
          if [ -n "$component" ]; then
            echo "Installing component: $component"
            rustup component add "$component"
          fi
        done

    - name: Install cargo tools
      if: inputs.tools != ''
      uses: taiki-e/install-action@e7ef886cf8f69c25ecef6bbc2858a42e273496ec # v2.62.28
      with:
        tool: ${{ inputs.tools }}

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "."
        cache-all-crates: true
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}${{ inputs.cache-key }}