# Test Case: Web Fonts
name = "Web Font Loading"
description = "Query about implementing web font loading"
query = "add support for @font-face and web font loading"
project_root = "benchmarks/test_repositories/valor"

[[expected]]
path = "crates/css/modules/fonts/src/lib.rs"
priority = "critical"
reason = "Font module"

[[expected]]
path = "crates/renderer/wgpu_backend/src/text.rs"
priority = "high"
reason = "Text rendering with fonts"

[[expected]]
path = "crates/css/src/parser.rs"
priority = "medium"
reason = "Parsing @font-face"
