# Test Case: HTML Parsing
name = "HTML Parse Error Recovery"
description = "Query about HTML parser error recovery"
query = "how does the parser recover from malformed HTML tags"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

[[expected]]
path = "crates/html/src/parser.rs"
priority = "critical"
reason = "HTML parser implementation"

[[expected]]
path = "crates/html/src/lib.rs"
priority = "high"
reason = "HTML module"

[[expected]]
path = "crates/html/src/tokenizer.rs"
priority = "medium"
reason = "HTML tokenizer"
