# Test Case: GPU Text Rendering
name = "GPU Text Rendering"
description = "Query about debugging text rendering artifacts"
query = "debug text rendering artifacts on GPU backend"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

[[expected]]
path = "crates/renderer/wgpu_backend/src/text.rs"
priority = "critical"
reason = "GPU text rendering"

[[expected]]
path = "crates/renderer/wgpu_backend/src/state/text.rs"
priority = "critical"
reason = "Text rendering state"

[[expected]]
path = "crates/renderer/src/display_list.rs"
priority = "high"
reason = "Display list"

[[expected]]
path = "crates/css/modules/text/src/lib.rs"
priority = "medium"
reason = "CSS text module"
