# Test Case: Async Rendering Pipeline
name = "Async Rendering Pipeline"
description = "Implement async rendering to avoid blocking"
query = "implement async rendering to prevent main thread blocking"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

# Expected relevant files
[[expected]]
path = "crates/renderer/src/renderer.rs"
priority = "critical"
reason = "Main renderer implementation"

[[expected]]
path = "crates/renderer/wgpu_backend/src/state.rs"
priority = "critical"
reason = "GPU backend state management"

[[expected]]
path = "crates/page_handler/src/lib.rs"
priority = "high"
reason = "Page rendering coordination"

[[expected]]
path = "crates/renderer/src/lib.rs"
priority = "medium"
reason = "Renderer module exports"

# Files that should NOT appear
[[excluded]]
path = "crates/html/src/parser"
reason = "HTML parsing, not rendering"

[[excluded]]
path = "crates/css/modules/selectors"
reason = "CSS selectors, not async rendering"
