# Test Case: Console Logging
name = "Console Logging Implementation"
description = "Bug fix query about console.log not working"
query = "fix console.log output not appearing in debug mode"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

# Expected relevant files
[[expected]]
path = "crates/js/src/console.rs"
priority = "critical"
reason = "Console API implementation"

[[expected]]
path = "crates/js/src/bindings/logger.rs"
priority = "critical"
reason = "Logger bindings for JavaScript"

[[expected]]
path = "crates/js/src/runtime.rs"
priority = "high"
reason = "Runtime setup and configuration"

[[expected]]
path = "crates/js/src/lib.rs"
priority = "medium"
reason = "JS module exports"

# Files that should NOT appear
[[excluded]]
path = "crates/html"
reason = "HTML parsing, not logging"

[[excluded]]
path = "crates/css"
reason = "CSS styling, not console"
