# Test Case: CSS Parsing Implementation
name = "CSS Parsing Implementation"
description = "Query about how CSS is parsed in the browser engine"
query = "how does CSS parsing work"
project_root = "benchmarks/test_repositories/valor"

# Expected relevant files
[[expected]]
path = "crates/css/modules/cascade/src/lib.rs"
priority = "critical"
reason = "CSS cascade and parsing logic"

[[expected]]
path = "crates/css/modules/core/src/lib.rs"
priority = "critical"
reason = "Core CSS module implementation"

[[expected]]
path = "crates/css/orchestrator/src/lib.rs"
priority = "high"
reason = "CSS orchestration and coordination"

[[expected]]
path = "crates/css/modules/selectors"
priority = "medium"
reason = "CSS selector parsing and matching"

[[expected]]
path = "crates/css/modules/box/src/lib.rs"
priority = "medium"
reason = "CSS box model properties"

# Files that should NOT appear
[[excluded]]
path = "crates/renderer/wgpu_backend"
reason = "Rendering backend, not parsing"

[[excluded]]
path = "crates/html"
reason = "HTML parsing, different domain"

[[excluded]]
path = "crates/js"
reason = "JavaScript engine, not CSS"
