# Test Case: DOM Tree Management
name = "DOM Tree Management"
description = "Query about DOM tree structure and manipulation"
query = "where is the DOM tree built and modified"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

# Expected relevant files
[[expected]]
path = "crates/html/src/parser/html5ever_engine.rs"
priority = "critical"
reason = "HTML5 parser engine that builds the DOM tree"

[[expected]]
path = "crates/html/src/dom/mod.rs"
priority = "critical"
reason = "DOM node structure and tree representation"

[[expected]]
path = "crates/html/src/parser/mod.rs"
priority = "high"
reason = "HTML parser module"

[[expected]]
path = "crates/page_handler/src/document.rs"
priority = "high"
reason = "Document interface for DOM manipulation"

[[expected]]
path = "crates/html/src/lib.rs"
priority = "medium"
reason = "HTML module exports"

# Files that should NOT appear
[[excluded]]
path = "crates/css"
reason = "CSS styling, not DOM structure"

[[excluded]]
path = "crates/renderer"
reason = "Rendering, not DOM tree building"

[[excluded]]
path = "crates/js/js_engine_v8"
reason = "JavaScript engine, not DOM tree"
