# Test Case: JavaScript Runtime Integration
name = "JavaScript Runtime Integration"
description = "Query about JavaScript execution and runtime setup"
query = "how does the JavaScript runtime integrate with the DOM"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

# Expected relevant files
[[expected]]
path = "crates/js/src/runtime.rs"
priority = "critical"
reason = "JavaScript runtime implementation"

[[expected]]
path = "crates/js/src/lib.rs"
priority = "critical"
reason = "JS module entry point"

[[expected]]
path = "crates/js/src/bindings/dom.rs"
priority = "high"
reason = "DOM bindings for JavaScript"

[[expected]]
path = "crates/js/src/dom_index.rs"
priority = "high"
reason = "DOM indexing for JS access"

[[expected]]
path = "crates/page_handler/src/lib.rs"
priority = "medium"
reason = "Page handler coordination"

# Files that should NOT appear
[[excluded]]
path = "crates/css"
reason = "CSS styling, not JS runtime"

[[excluded]]
path = "crates/renderer/wgpu_backend"
reason = "Rendering backend, not JS integration"
