# Test Case: Layout Engine
name = "Layout Engine"
description = "Query about the layout engine and box model"
query = "implement flexbox layout algorithm"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

# Expected relevant files
[[expected]]
path = "crates/css/modules/flexbox/src/lib.rs"
priority = "critical"
reason = "Flexbox CSS module implementation"

[[expected]]
path = "crates/css/modules/core/src/8_box_model"
priority = "critical"
reason = "CSS box model implementation"

[[expected]]
path = "crates/css/modules/display"
priority = "high"
reason = "CSS display property handling"

[[expected]]
path = "crates/css/modules/position/src/lib.rs"
priority = "medium"
reason = "CSS positioning properties"

[[expected]]
path = "crates/css/src/layout_helpers.rs"
priority = "medium"
reason = "Layout helper functions"

[[expected]]
path = "crates/renderer/src/lib.rs"
priority = "low"
reason = "Renderer module structure"

# Files that should NOT appear
[[excluded]]
path = "crates/html/src/parser.rs"
reason = "HTML parsing, not layout"

[[excluded]]
path = "crates/js"
reason = "JavaScript engine, not layout"

[[excluded]]
path = "crates/renderer/wgpu_backend"
reason = "GPU rendering backend, not layout algorithm"
