# Test Case: CSS Selector Performance
name = "CSS Selector Performance"
description = "Performance optimization query"
query = "optimize CSS selector matching for large DOMs"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

# Expected relevant files
[[expected]]
path = "crates/css/modules/selectors/src/lib.rs"
priority = "critical"
reason = "Selector matching implementation"

[[expected]]
path = "crates/css/modules/selectors/src/matching.rs"
priority = "critical"
reason = "Selector matching algorithm"

[[expected]]
path = "crates/css/modules/cascade/src/lib.rs"
priority = "high"
reason = "Cascade algorithm with selector matching"

[[expected]]
path = "crates/html/src/dom/mod.rs"
priority = "medium"
reason = "DOM structure being queried"

# Files that should NOT appear
[[excluded]]
path = "crates/renderer"
reason = "Rendering, not selector matching"

[[excluded]]
path = "crates/js"
reason = "JavaScript, not CSS selectors"
