# Test Case: Configuration Management
name = "Configuration Management"
description = "Query about configuration loading and management"
query = "how is configuration loaded and managed"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

# Expected relevant files
[[expected]]
path = "crates/config/src/lib.rs"
priority = "critical"
reason = "Configuration management module"

[[expected]]
path = "crates/config/src/loader.rs"
priority = "critical"
reason = "Configuration loading logic"

[[expected]]
path = "crates/config/src/validation.rs"
priority = "high"
reason = "Configuration validation"

[[expected]]
path = "crates/core/src/settings.rs"
priority = "medium"
reason = "Application settings"

# Files that should NOT appear
[[excluded]]
path = "crates/js"
reason = "JavaScript engine, not configuration"

[[excluded]]
path = "examples/"
reason = "Example code, not core implementation"
