# Test Case: Networking Layer
name = "Networking Layer"
description = "Query about network requests and protocols"
query = "how are network requests handled"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

# Expected relevant files
[[expected]]
path = "crates/network/src/lib.rs"
priority = "critical"
reason = "Network module"

[[expected]]
path = "crates/network/src/http.rs"
priority = "critical"
reason = "HTTP client implementation"

[[expected]]
path = "crates/network/src/connection.rs"
priority = "high"
reason = "Connection management"

[[expected]]
path = "crates/network/src/protocol.rs"
priority = "medium"
reason = "Protocol handling"

# Files that should NOT appear
[[excluded]]
path = "crates/css"
reason = "CSS parsing, not networking"

[[excluded]]
path = "crates/dom"
reason = "DOM tree, not networking"
