# Test Case: Relative Positioning
name = "CSS Positioning"
description = "Query about relative positioning"
query = "how is relative positioning calculated"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

[[expected]]
path = "crates/css/modules/core/src/9_visual_formatting/part_9_4_3_relative_positioning.rs"
priority = "critical"
reason = "Relative positioning implementation"

[[expected]]
path = "crates/css/modules/positioned_layout/src/lib.rs"
priority = "high"
reason = "Positioned layout module"

[[expected]]
path = "crates/css/modules/core/src/lib.rs"
priority = "medium"
reason = "CSS core"
