# Test Case: Testing Framework
name = "Testing Framework"
description = "Query about test utilities and helpers"
query = "how are tests structured and run"
project_root = "benchmarks/crates/quality/test_repositories/valor"

[repository]
url = "https://github.com/BigBadE/Valor.git"
commit = "367ecde76cfe1a587256f9c6f318a56afee5ac17"

# Expected relevant files
[[expected]]
path = "crates/test_utils/src/lib.rs"
priority = "critical"
reason = "Test utilities module"

[[expected]]
path = "crates/test_utils/src/fixtures.rs"
priority = "high"
reason = "Test fixtures"

[[expected]]
path = "crates/test_utils/src/mocks.rs"
priority = "high"
reason = "Mock implementations"

[[expected]]
path = "crates/core/src/test_helpers.rs"
priority = "medium"
reason = "Core test helpers"

# Files that should NOT appear
[[excluded]]
path = "crates/renderer"
reason = "Rendering, not testing"

[[excluded]]
path = "examples/"
reason = "Examples, not test framework"
