[package]
name = "merlin-routing"
version.workspace = true
edition.workspace = true

[dependencies]
merlin-core.workspace = true
merlin-providers.workspace = true
merlin-local.workspace = true
async-trait.workspace = true
tokio.workspace = true
uuid.workspace = true
petgraph.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tui-textarea.workspace = true
textwrap.workspace = true
flate2.workspace = true
tempfile.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[dev-dependencies]
tokio-test.workspace = true
criterion.workspace = true

[[bench]]
name = "routing_benchmarks"
harness = false

[lints]
workspace = true
