[package]
name = "agentic-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
reqwest = "0.12"
serde_json = "1"
toml = "0.8"

[lints]
workspace = true
