[package]
name = "agentic-context"
version.workspace = true
edition.workspace = true

[dependencies]
agentic-core.workspace = true
agentic-languages.workspace = true
walkdir.workspace = true
tracing.workspace = true

[lints]
workspace = true
