[package]
name = "rust-backend"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
merlin-core.workspace = true
merlin-deps.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]

