name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  deployments: write
  pull-requests: write

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bigbade/agentic_optimizer/ci:latest
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gungraun benchmarks
        run: |
          cargo bench -p merlin-benchmarks-gungraun --bench gungraun_integration --bench gungraun_routing 2>&1 | tee gungraun-output.txt
          if grep -q "FAILED" gungraun-output.txt; then
            echo "Benchmark failures detected"
            exit 1
          fi

      - name: Prepare gh-pages workspace
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Parse benchmark results to JSON
        run: |
          python3 scripts/parse-benchmarks.py \
            --gungraun-output gungraun-output.txt \
            --output-dir benchmark-data \
            --history-source gh-pages/data

      - name: Upload parsed JSON
        uses: actions/upload-artifact@v4
        with:
          name: gungraun-json-results
          path: benchmark-data/gungraun/latest.json
          retention-days: 90
          if-no-files-found: warn

      - name: Publish Gungraun results to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && hashFiles('benchmark-data/gungraun/latest.json') != ''
        run: |
          set -e
          ts=$(date +%Y-%m-%d-%H-%M-%S)

          # Switch to gh-pages branch
          cd gh-pages

          # Create directories
          mkdir -p data/gungraun

          # Copy pre-generated JSON data
          if [ -f ../benchmark-data/gungraun/latest.json ]; then
            cp ../benchmark-data/gungraun/latest.json data/gungraun/
            # Also save timestamped version for history
            cp ../benchmark-data/gungraun/latest.json "data/gungraun/${ts}.json"
          fi

          # Generate dashboard if it doesn't exist
          if [ ! -f index.html ]; then
            cd ..
            bash scripts/generate-benchmark-dashboard.sh /tmp/dashboard-temp
            cd gh-pages
            cp /tmp/dashboard-temp/index.html .
            cp -r /tmp/dashboard-temp/assets .
          fi

          # Commit and push
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/ index.html assets/ || true
          git commit -m "Update Gungraun benchmark results: ${ts}" || echo "No changes to commit"
          git pull --rebase origin gh-pages || true
          git push origin gh-pages
