name: Benchmarks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# Cancel in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  deployments: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for comparison

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          profile: release

      - name: Run benchmarks
        run: cargo bench --workspace --no-fail-fast --profile release

      - name: Commit results to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          mkdir -p perf-bench
          cp -r target/criterion perf-bench/$(date +%Y-%m-%d-%H-%M-%S) || echo "No criterion results"
          git add perf-bench/
          git commit -m "Update performance benchmark results" || echo "No changes to commit"
          git push origin gh-pages

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion/
          retention-days: 90
