name: Performance Benchmarks

on:
  push:
    branches: [ master ]
    paths:
      - 'benchmark-data/perf-latest.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  deployments: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  performance-benchmark:
    name: Publish Performance Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for benchmark JSON
        id: check_results
        run: |
          if [ ! -f benchmark-data/perf-latest.json ]; then
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "❌ No benchmark JSON found at benchmark-data/perf-latest.json"
            echo ""
            echo "To generate benchmark results locally:"
            echo "  1. cargo bench --workspace"
            echo "  2. python3 scripts/parse-benchmarks.py --criterion-dir target/criterion --output-dir benchmark-data"
            echo "  3. git add benchmark-data/perf-latest.json"
            echo "  4. git commit -m 'Update performance benchmarks'"
            exit 1
          else
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "✅ Found benchmark JSON"
            cat benchmark-data/perf-latest.json | head -30
          fi

      - name: Upload results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-benchmark-results
          path: benchmark-data/perf-latest.json
          retention-days: 90
          if-no-files-found: warn

      - name: Prepare gh-pages workspace
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Publish performance results to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && hashFiles('benchmark-data/perf-latest.json') != ''
        run: |
          set -e
          ts=$(date +%Y-%m-%d-%H-%M-%S)

          # Switch to gh-pages branch
          cd gh-pages

          # Create directories
          mkdir -p data

          # Copy pre-generated JSON data
          if [ -f ../benchmark-data/perf-latest.json ]; then
            cp ../benchmark-data/perf-latest.json data/
            # Also save timestamped version for history
            cp ../benchmark-data/perf-latest.json "data/perf-${ts}.json"
          fi

          # Generate dashboard if it doesn't exist
          if [ ! -f index.html ]; then
            cd ..
            bash scripts/generate-benchmark-dashboard.sh /tmp/dashboard-temp
            cd gh-pages
            cp /tmp/dashboard-temp/index.html .
            cp -r /tmp/dashboard-temp/assets .
          fi

          # Commit and push
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/ index.html assets/ || true
          git commit -m "Update performance benchmark results: ${ts}" || echo "No changes to commit"
          git pull --rebase origin gh-pages || true
          git push origin gh-pages
