name: Build Commit Image

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: [ Build Container ]   # exact name from build-container.yml
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:
  build-commit-image:
    # Skip if we're rebuilding the base image
    if: !contains(github.event.head_commit.modified, 'Cargo.toml')
    name: Build incremental commit image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short commit SHA
        id: sha
        run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push commit image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/Dockerfile.commit
          push: true
          tags: |
            ghcr.io/bigbade/agentic_optimizer/ci:latest
          build-args: |
            BASE_IMAGE=ghcr.io/bigbade/agentic_optimizer/ci:base
            COMMIT_SHA=${{ github.sha }}
          cache-from: |
            type=registry,ref=ghcr.io/bigbade/agentic_optimizer/ci:latest
            type=gha
          cache-to: type=gha,mode=max
