name: Update Dependencies

on:
  schedule:
    - cron: "0 0 * * 0"  # Run weekly on Sunday at midnight UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install latest nightly Rust
        run: rustup toolchain install nightly --profile minimal --component clippy rustfmt --no-self-update

      - name: Get nightly version
        id: nightly_version
        run: |
          NIGHTLY_DATE=$(rustup toolchain list | grep nightly | head -1 | sed 's/nightly-\([0-9-]*\).*/\1/')
          echo "date=${NIGHTLY_DATE}" >> $GITHUB_OUTPUT
          echo "Latest nightly: ${NIGHTLY_DATE}"

      - name: Update rust-toolchain.toml
        run: |
          sed -i 's/channel = "nightly-[0-9-]*"/channel = "nightly-${{ steps.nightly_version.outputs.date }}"/' rust-toolchain.toml
          cat rust-toolchain.toml

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          components: clippy

      - name: Update Cargo.lock
        run: cargo update

      - name: Run clippy on latest nightly
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
        continue-on-error: true

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet rust-toolchain.toml Cargo.lock; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update to nightly-${{ steps.nightly_version.outputs.date }} and dependencies"
          title: "Update to nightly-${{ steps.nightly_version.outputs.date }}"
          body: |
            Automated weekly update to latest Rust nightly toolchain and dependencies.

            - Updated `rust-toolchain.toml` to `nightly-${{ steps.nightly_version.outputs.date }}`
            - Updated `Cargo.lock` dependencies via `cargo update`
            - Clippy validation: ${{ steps.clippy.outcome }}

            🤖 Generated by weekly dependencies update workflow
          branch: update-nightly-${{ steps.nightly_version.outputs.date }}
          delete-branch: true
          labels: dependencies,automated
