name: IAI-Callgrind Benchmarks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  deployments: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  iai-callgrind-benchmark:
    name: Run IAI-Callgrind Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          profile: release

      - name: Run IAI-Callgrind benchmarks
        run: |
          cargo run --profile ci-release --bin perf-bench -- --iai --output iai-results.md
          echo " IAI-Callgrind benchmarks completed"
          if [ -f iai-results.md ]; then
            head -30 iai-results.md
          else
            echo " Warning: iai-results.md not found"
          fi

      - name: Upload results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: iai-callgrind-benchmark-results
          path: iai-results.md
          retention-days: 90
          if-no-files-found: warn

      - name: Prepare gh-pages workspace
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Publish IAI-Callgrind results to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && hashFiles('iai-results.md') != ''
        run: |
          set -e
          ts=$(date +%Y-%m-%d-%H-%M-%S)
          mkdir -p gh-pages/iai-callgrind-bench
          cp iai-results.md gh-pages/iai-callgrind-bench/latest.md
          cp iai-results.md "gh-pages/iai-callgrind-bench/${ts}.md"
          cd gh-pages
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add iai-callgrind-bench/
          git commit -m "Update IAI-Callgrind benchmark results: ${ts}" || echo "No changes to commit"
          git push origin gh-pages
