name: Quality Benchmarks

on:
  push:
    branches: [ master ]
    paths:
      - 'benchmarks/data/quality/latest.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  deployments: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  quality-benchmark:
    name: Run Quality Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: quality-benchmark-results
          path: benchmarks/data/quality-results.md
          retention-days: 90

      - name: Prepare gh-pages workspace
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Upload parsed JSON
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: quality-json-results
          path: benchmark-data/quality/latest.json
          retention-days: 90
          if-no-files-found: warn

      - name: Publish quality results to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && hashFiles('benchmark-data/quality/latest.json') != ''
        run: |
          set -e
          ts=$(date +%Y-%m-%d-%H-%M-%S)

          # Switch to gh-pages branch
          cd gh-pages

          # Create directories
          mkdir -p data/quality

          # Copy pre-generated JSON data
          if [ -f ../benchmark-data/quality/latest.json ]; then
            cp ../benchmark-data/quality/latest.json data/quality/
            # Also save timestamped version for history
            cp ../benchmark-data/quality/latest.json "data/quality/${ts}.json"
          fi

          # Generate dashboard if it doesn't exist
          if [ ! -f index.html ]; then
            cd ..
            bash scripts/generate-benchmark-dashboard.sh /tmp/dashboard-temp
            cd gh-pages
            cp /tmp/dashboard-temp/index.html .
            cp -r /tmp/dashboard-temp/assets .
          fi

          # Commit and push
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/ index.html assets/ || true
          git commit -m "Update quality benchmark results: ${ts}" || echo "No changes to commit"
          git pull --rebase origin gh-pages || true
          git push origin gh-pages

      # Don't remove benchmarks/data/quality-results.md - keep it for manual review and re-runs

