name: Quality Benchmarks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  deployments: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  quality-benchmark:
    name: Run Quality Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          profile: release

      - name: Build quality benchmark binary
        run: cargo build --release --bin quality-bench

      - name: Run quality benchmarks
        run: cargo run --release --bin quality-bench -- --output quality-results.md

      - name: Ensure results file exists
        run: |
          if [ ! -f quality-results.md ]; then
            echo "# Context Quality Benchmark Results" > quality-results.md
            echo "No results were generated (no test cases found or all filtered)." >> quality-results.md
          fi
          echo "Generated files:" && ls -la

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: quality-benchmark-results
          path: quality-results.md
          retention-days: 90

      - name: Prepare gh-pages workspace
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Publish quality results to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          set -e
          ts=$(date +%Y-%m-%d-%H-%M-%S)
          mkdir -p gh-pages/quality-bench
          cp quality-results.md gh-pages/quality-bench/latest.md
          cp quality-results.md "gh-pages/quality-bench/${ts}.md"
          cd gh-pages
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add quality-bench/
          git commit -m "Update quality benchmark results: ${ts}" || echo "No changes to commit"
          git push origin gh-pages

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('quality-results.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '## Quality Benchmark Results\n\n' + results
            });
