name: Quality Benchmarks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  deployments: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  quality-benchmark:
    name: Run Quality Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          profile: release

      - name: Build quality benchmark binary
        run: cargo build --release --bin quality-bench

      - name: Run quality benchmarks
        run: cargo run --release --bin quality-bench -- --output quality-results.md

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: quality-benchmark-results
          path: quality-results.md
          retention-days: 90

      - name: Commit results to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          mkdir -p quality-bench
          cp quality-results.md quality-bench/latest.md
          cp quality-results.md quality-bench/$(date +%Y-%m-%d-%H-%M-%S).md
          git add quality-bench/
          git commit -m "Update quality benchmark results" || echo "No changes to commit"
          git push origin gh-pages

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('quality-results.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '## Quality Benchmark Results\n\n' + results
            });
