name: Tests

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Cancel in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_CODEGEN_BACKEND: llvm

jobs:
  test:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          profile: debug
          components: clippy, rustfmt

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run tests with coverage
        run: cargo build --verbose && cargo llvm-cov --lcov --output-path coverage.info --ignore-filename-regex "test_repositories|benchmarks" --all-features --workspace --no-fail-fast --lib --bins --tests --verbose -- --nocapture

      - name: Upload coverage to Codecov
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.info
          verbose: true
          fail_ci_if_error: false