name: Tests

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Cancel in-progress runs when a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0  # Disable incremental compilation to save disk space

jobs:
  test:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          profile: ci
          components: clippy, rustfmt

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run tests with coverage
        run: cargo build --profile ci --verbose && cargo llvm-cov --profile ci --lcov --output-path coverage.info --ignore-filename-regex "test_repositories|benchmarks" --all-features --workspace --no-fail-fast --lib --bins --tests --verbose -- --nocapture

      - name: Clean up build artifacts to free disk space
        if: always()
        run: |
          # Remove build artifacts but keep dependencies
          rm -rf target/ci/deps/*.d target/ci/deps/*.o 2>/dev/null || true
          # Remove test executables
          find target/ci -type f -executable -delete 2>/dev/null || true
          # Show remaining disk usage
          df -h

      - name: Upload coverage to Codecov
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.info
          verbose: true
          fail_ci_if_error: false